### ISSUE TITLE
Article Edit Button Disappears on Mobile in the Denim Themes

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#1077] opened 2020-10-19 17:27 UTC
Issue first mentioned in the Geeklog Forum: https://www.geeklog.net/forum/viewtopic.php?showtopic=97315

Should check both the Denim and Denim 3 themes for issue.

To save space the edit icon disappears from the page on mobile devices but that means it is not easy for an admin on a mobile device to edit an article. It should remain.

We should also add Edit Article for those with access to the Article Options (like we do for other admin options like Send Ping)

**Comment by mystralkk** [comment] 2022-01-14 06:14
Fixed with change set 8e5c8528a23dc3611f2cae6086f26dc4d6679cf7.  The cause of this issue was:
```CSS
@media only screen and (max-width: 959px) {

  .story_icon {
    display: none;
  }
}
```

**Comment by eSilverStrike** [comment] 2022-01-17 18:28
@mystralkk Notice some really weird styles messing from pages in the denim theme like the post a comment button and command and control page and the Denim Curve theme being completely broken (and all the other themes having some issues).

Took a while as I could not understand why it wasn't working as the classes are in the css files and should have been applied by the browser. 

Looks like the issue is from commit 8e5c8528a23dc3611f2cae6086f26dc4d6679cf7 

It deals with commenting out the whole media query. When you do that it creates problems for some reason (nothing mentioned online that I could find about not commenting out media queries). Commenting out the content in the media query only (or just deleting the media query entirely) fixes the css issues.

Not sure how you want to handle this fix as you also updated the source files  as well in the "src" directory.

**Comment by mystralkk** [comment] 2022-01-18 02:13
Sorry, my mistake.  I fixed it again.

**Closed** 2022-01-19 15:06 UTC
Labels: Geeklog Themes, Improvement
