### ISSUE TITLE
After Upgrade Users May have Login Issues

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#995] opened 2019-11-19 18:37 UTC
I get a blank screen sometimes

Also, if I am not currently logged in it looks like it tries and I get speed limit errors

This has happened to me several times. I think it is the new session class getting confused with old cookies stored on the users browser. Once I clear the browsers cookies for the website things start to work fine.

If it is a blank screen, turning on root debug the error gets reported as:

```
E_WARNING(2) - Use of undefined constant XHTML - assumed 'XHTML' (this will throw an Error in a future version of PHP) @ /usr/home/geeklog/geeklog/language/english_utf-8.php line 475
Call Stack
#	Function			File							Line
1	require_once			/usr/home/geeklog/public_html/lib-common.php		7014
2	COM_displayMessageAndAbort	/usr/home/geeklog/geeklog/system/lib-sessions.php	433
3	SESS_handleAutoLogin		/usr/home/geeklog/geeklog/system/lib-sessions.php	132
4	SESS_sessionCheck		/usr/home/geeklog/public_html/lib-common.php		256
5	require_once			/usr/home/geeklog/public_html/index.php			37

```

**Comment by eSilverStrike** [comment] 2019-11-21 16:25
@mystralkk just a quick look at this as I was wondering if this was happening (at least the speed limit errors) because I was logged in under Geeklog v2.2.0 and then I upgraded (I think it also happens on migration) to Geeklog v2.2.1. At this point since the session handling has change is the  Permanent Cookie Name (cookie_name) contain an incorrect value because we are now using PHP Session handling which then results in the SESS_handleAutoLogin creating a speed limit issue? Is there a way to fix this? One option could be in the installer on the upgrade warning page include one about sessions and that the admin may have to delete the cookies for their website in order to be able to login.

**Comment by mystralkk** [comment] 2019-11-21 22:30
As a trial fix for this issue, clearing speed limits for login during the install/upgrade/migrate process would be the answer.  So change set 61f0f58.

**Comment by eSilverStrike** [comment] 2019-11-22 11:59
Not sure if it will work but I will give it a test when I retest the install/migrate after I update things for the theme check issue #996 . 

I know sometimes I could travel around the site a bit before the speedlimit would get triggered (I assume on each page I visited would be where the autologin failed and then added a login record to the speedlimit table)

**Comment by eSilverStrike** [comment] 2019-11-22 14:30
Okay I triggered the speed limit issue again while using Geeklog with multiple browsers (ie IE and Firefox). I think I know what is going on.

I have been doing testing and have logged into Geeklog twice from 2 different browsers which then sets the autologin_key. In previous versions of Geeklog I could do this but when it happens now, the browser that logged in first when I use it again automatically logs me out and gives the speed limit error right away. This is because the autologin key is incorrect as a new one was created by the second browser logging in. The only way to login via the other browser is to delete the cookies.

This issue would also happen if you log into Geeklog using different devices.

**Comment by mystralkk** [comment] 2019-11-22 20:52
So, it would be necessary to let users have multiple autologin keys to allow them to login with different browsers and/or devices at the same time.  To do this, we would have to create a new table such as `gl_autologin_keys`, with user id, autologin key, user agent, and IP fields.

**Comment by eSilverStrike** [comment] 2019-11-22 21:31
Curious how did the auto login work before we moved to the PHP Session Handler? Thinking about it I guess the key was stored in the session table (as a seperate session) so that was how it was able to work on multiple devices and browsers.

We should not have to store the user agent or IP fields would we? Just a date field for the user "Remember me for" field. This field we would use to trim the autologins once they expire.

If the user logs in successfully then create an autologin key in the table. If the user logs out of that session we then can delete the autologin key for that session. If the user logins in under different devices  he would have several auto login keys in the table. 

When the user comes back at a later date then we can check to see if the autologin key exists (and not expired). I don't think it wouldn't really matter about the IP and stuff as that could change over time. If it does exist the user is logged in, if it does not exist then he is not logged in (and we don't use the speed limiter with it).

Does that sound right or did I miss something?

**Comment by mystralkk** [comment] 2019-11-22 22:53
That sounds good to me as well.

**Comment by eSilverStrike** [comment] 2019-11-23 02:20
Actually can't we just use the updated session table like before and add the autologin key on it? Since the user could have multiple sessions from different devices/browsers that should work out perfectly since the key will be stored in the same session record.

**Comment by mystralkk** [comment] 2019-11-25 11:56
I hope change set 007a207 will work.

**Comment by eSilverStrike** [comment] 2019-11-25 12:06
I will test it out after I finish up with the valid theme issue.

**Comment by eSilverStrike** [comment] 2019-11-25 17:52
Just did some testing and somethings not quit right when I am watching the sessions table while logging in and out:

**First Issue**
- First time I visit site a session record is created in the sessions table that matches the session cookie in my browser
- I then log into the site and a new session record is created with a new sess_id that matches the new session cookie in my browser. The old session record is not deleted though from before from the sessions table. Couldn't we just reuse the original sess_id instead of creating a new one?

**Second Issue**
- When I log into the site from 2 different browsers (using the same user) I have 2 session records with autologin_keys that match the session cookies on the 2 browsers. This looks good.
- I then log out of the site from one of the browsers. Both session records disappear from the sessions table for some reason. I should still have the one session record for the session I did not log out of.

**Comment by eSilverStrike** [comment] 2019-11-26 15:50
Thanks. I have done some testing and all looks good so far.  I also fixed an old bug dealing with Google Chrome. 

I noticed that the autologin_key updates on every page load. Does this need to be done for security reasons? Just wondering

**Comment by mystralkk** [comment] 2019-11-27 11:42
With change set fd24cfc, the auto-login key gets updated only when the user logged in and logged out.

**Comment by eSilverStrike** [comment] 2019-11-27 15:31
I was having more issues but it dealt with my fix for #465. I had to back out my Google Chrome fix for Cookie Domains as IP as it made Firefox and Edge not able to set cookies properly for domains that are IPs. For more info see #465

Still testing. Will update once complete.

**Comment by eSilverStrike** [comment] 2019-11-27 18:22
@mystralkk - Well testing this is taking me longer than I planned 😉. It didn't help that I introduced a bug with using Firefox, with my Google Chrome fix (which I since have reverted). I want to give the sessions a real good once over since it is an important part of the Geeklog Security.

I added some code to the session function to add in a record to the Geeklog Session table if it for some reasons goes missing as the rest of the functions for updating the columns didn't check for this.

I was looking into the autologin_key and potential hackers trying to manipulate the cookie in the browser. I see if I change the cookie value it does get changed back which is good. 

I did notice though that deleting the autologin_key cookie of a logged in user results in the autologin_key column in our sessions table to be updated to empty. We should recreate this cookie instead. I didn't have a chance to fix this as I have run out of time today.

Is there any further testing with this you think? Once the above is fixed along with #1001 which I have not gotten to yet I will release Beta 3. Sound good?

**Comment by mystralkk** [comment] 2019-11-27 20:59
> I did notice though that deleting the autologin_key cookie of a logged in user results in the autologin_key column in our sessions table to be updated to empty. We should recreate this cookie instead. I didn't have a chance to fix this as I have run out of time today.

I don't think we should recreate autologin key cookie.  It is the only thing that proves that its owner is allowed to login to the site automatically.  Thus, users who have lost it by accident or by design should login in the normal way.

**Comment by eSilverStrike** [comment] 2019-11-27 23:12
Okay I fixed a bug where if the autologin_key cookie was missing, the autologin_key in our sessions table would be set to an empty string (a new one is generated now). We don't want someone then creating an empty autologin key cookie and be able to login for a user potentially. 

This fix also does recreate the auto login key if the cookie doesn't equal the one in the database. I didn't read your comment until after about this. We could change it but I don't see the issue as from the looks of the code the autologin_key only gets generated when the user has been confirmed to be logged in and valid.

I also confirmed that when the PHP Session has expired, the autologin_key cookie if incorrect, does not login the user. To simulate this I just deleted the session file in the php temp folder.

I did find one bug from this which I will need to take a closer look at when I get a chance (unless you have the time before me). If the PHP Session has expired and the autologin keys are correct a new session is created but I notice the record in our sessions table is missing the autologin_key (it is empty). The old session is still their with the existing autologin key. We need to delete the old session record from our session table if the autologin key is used and then either apply that key (or generate a new one) for the new session since the user did auto login.

**Comment by eSilverStrike** [comment] 2019-11-28 15:02
Okay I think I am finished with the fixes. No extra session records get kept around and the autologin key gets updated when needed

Tested to see if users on multiple browsers stay logged using a domain (assigned in hosts file) as well as using an IP instead of a domain.

Also tested to see if autologin works (or doesn't work if cookie is incorrect) in similar situations as above.

@mystralkk Did you want to do any extra testing on my fixes or should we close the issue now?

**Comment by mystralkk** [comment] 2019-11-28 20:56
Let's close the issue.

**Closed** 2019-11-28 21:27 UTC
Labels: Bug
