### ISSUE TITLE
textarea and topic select of the article editing is width longer than container by smartphone.

### ISSUE THREAD

**Issue by milk54** [Geeklog-Core/geeklog#924] opened 2019-02-08 06:56 UTC
textarea and select of topic of the article editingin in theme denim is width longer than container by smartphone.

I think that it is better to modify that textarea fix width by css, select of topic change display:block.

**Comment by eSilverStrike** [comment] 2019-02-08 14:56
Did you want to do a pull request?

**Comment by milk54** [comment] 2019-02-08 15:41
No, I'd like the core theme developer（@dengenxp） to fix it.

**Comment by eSilverStrike** [comment] 2019-10-04 14:55
I checked both the denim theme and denim3 theme and it appears to work fine in Firefox and on Chrome. For the article editor both the textarea and topic select scale to the size of the viewport. 

Do you have any other information to add to see if I can reproduce this error?

**Comment by eSilverStrike** [comment] 2019-10-11 12:02
Cannot reproduce so closing.

**Closed by eSilverStrike** 2019-10-11 12:02 UTC
Labels: Bug, Geeklog Themes
