### ISSUE TITLE
Hidden is not saved in Topic Editor

### ISSUE THREAD

**Issue by 0MAL** [Geeklog-Core/geeklog#1097] opened 2021-09-23 11:02 UTC
Hidden is not saved in Topic Editor
<img width="772" alt="topichidden" src="https://user-images.githubusercontent.com/91258926/134496570-c3b6cfa9-9dd7-4f99-ae1f-557118c4c2c1.png">
.

**Comment by mystralkk** [comment] 2022-01-10 04:47
You cannot hide root topics.  Does this happen with child topics as well?

**Comment by eSilverStrike** [comment] 2022-01-10 12:03
I tested and was able to hide all child topics. Top level Topics (those in the root) cannot be hidden since they are the top level and do not have a parent. Hiding them would prevent a user from being able to select the topic and any topic below it.

Did I miss something in my testing Omal and are there cases where it doesn't work?

**Comment by mystralkk** [comment] 2022-01-10 12:10
Maybe Omal tried to hide top-level topics in vain.  If this is the case, this issue is not a bug, but we should have to make it clear that you cannot hide top-level topics in the topic editor.

**Comment by eSilverStrike** [comment] 2022-01-10 12:12
Yup. The current label sort of does at it mentions a parent topic but it may not be super clear.

**Comment by 0MAL** [comment] 2022-01-10 12:34
>Did I miss something in my testing Omal 
No, it is ok.
>but it may not be super clear
I agree.

**Comment by eSilverStrike** [comment] 2022-01-10 12:59
1) "Topic will be hidden in the Topic Block until it's Parent Topic is selected" (current label)

2) "Topic will be hidden in the Topic Block (if this Topic is a Child) until it's Parent Topic is selected"

3) "Topic is displayed in Topic Block only when Parent Topic is selected"

Hard to describe feature without a tool tip but I think number 3 is the best option.

**Comment by mystralkk** [comment] 2022-01-10 21:04
I agree number 3 is best.  In addition, it would be better to hide the "Hide" checkbox when the user selects the ROOT topic with the help of JavaScript.

**Comment by mystralkk** [comment] 2022-01-11 01:52
Implemented JavaScript part with change set 344b7512ce19dac13b6d95d6e4696f82f0234397.

**Comment by eSilverStrike** [comment] 2022-01-12 20:39
Noticed an issue. The hidden checkbox is not visible on the edit form when the page first loads up for a child topic. It only becomes visible if I change the parent topic select box.

**Comment by mystralkk** [comment] 2022-01-13 00:38
Fixed with change set 44781124da693194620f5b93e5c0805098a4971c.

**Closed** 2022-01-13 14:30 UTC
Labels: Bug
