### ISSUE TITLE
[Feature Requests] separation change user password dialog

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#533] opened 2016-01-06 13:13 UTC
**Reported by ktoto on 12 Sep 2011 20:04**

**Version:** 1.8.0

**Description:**
it will be good to remove password change dialog from "USer editor" to separate page. Because now if used "password save feature" in firefox it confusing web gui of geeklog. 
example :In field <password> firefox automatically fill data but in field "Password (again)" still nothing. Due to it if you change settings of user and press ok you receive "The new password does not match the confirmation password! "

[Mantis Bugtracker #1387](http://project.geeklog.net/tracking/view.php?id=1387)

**Comment by mystralkk** [comment] 2016-01-06 16:11
**Comment posted by dhaun on 12 Sep 2011 20:35**

There&#039;s an unofficial but widely supported HTML attribute to tell browsers not to auto-fill fields with that attribute. Maybe that would help here.

Anyone remember the name of that attribute?

**Comment by mystralkk** [comment] 2016-01-06 16:11
**Comment posted by mystralkk on 20 Sep 2011 11:34**

https://developer.mozilla.org/en/How_to_Turn_Off_form_Autocompletion

**Comment by eSilverStrike** [comment] 2018-04-02 13:28
I remember this happening before but I cannot reproduce it on Firefox, Edge or Chrome.

I also remember it happening in the Admin Create New User form (where it would fill in the password field automatically). It doesn't appear to be happening their anymore either so I am closing the issue (none of these forms have the autocomplete="off" as suggested by the above link).

I am closing the issue. It can be reopened if some one can reproduce the problem)

**Closed by eSilverStrike** 2018-04-02 13:28 UTC
Labels: feature
