### ISSUE TITLE
Confirm Geeklog and Core Plugins work with PHP 7.3 and Up minimum PHP requirement

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#944] opened 2019-06-23 19:57 UTC
- General testing to make sure Geeklog has no issues with PHP 7.3.
- DONE - Update docs to show support.
- DONE - Update docs to show minimum PHP version is PHP v5.6.4
- DONE - Update the install (if it tests for this) and the Geeklog Environment Checker.
- Confirm other plugins like Gus, Forum, Ban, Autotags, Downloads, etc... support PHP 7.3
- Update Geeklog Wiki at release with latest version info

**Comment by mystralkk** [comment] 2019-06-30 06:44
I did some research on system requirements of PHP-driven open source CMSs. 
https://docs.google.com/spreadsheets/d/1nO8y52UBuE-5RUDlWpB37qKumx4QZC5NYkZkLCLAa1k/edit?usp=sharing
Bumping up minimum PHP version to 5.6 seems quite reasonable to me.

**Comment by eSilverStrike** [comment] 2019-06-30 10:01
👍

Sounds good. Then confirmed lets up the min to PHP 5.6

Interesting seeing what the others supported.

**Comment by eSilverStrike** [comment] 2019-09-10 13:37
Updated docs and code with PHP min requirements. 

Still need to test Geeklog and other plugins with PHP 7.3

**Comment by mystralkk** [comment] 2019-09-28 09:16
I fixed some errors with GUS, and it seems to work fine with PHP 7.3.

**Comment by mystralkk** [comment] 2019-09-28 11:36
I fixed some errors with Ban, and it seems to work fine with PHP 7.3.

**Comment by eSilverStrike** [comment] 2019-09-28 13:46
Thanks I hope with in a next few weeks to replace my one development server that uses Windows Server 2003 and IIS (with PHP 5.6 and 7.0) with another machine that has Windows 10. It is super slow and can be difficult to switch PHP versions. 

I plan on installing WampServer on Windows 10 to make it easier for me to switch PHP versions so I can also  try out PHP 7.3 (never used something like WampServer before). What do you use WampServer or XAMPP (or something else?)

**Comment by mystralkk** [comment] 2019-09-28 14:13
I just installed Apache ( https://www.apachelounge.com ), MySQL and PHP separately on my PC (Windows 10).  This way it is easier to update PHP.

**Comment by mystralkk** [comment] 2019-10-01 10:58
I fixed some errors with Downloads, and it seems to work fine with PHP 7.3.

**Comment by eSilverStrike** [comment] 2019-10-01 11:18
How is Geeklog itself with PHP 7.3?

**Comment by mystralkk** [comment] 2019-10-01 11:27
I fixed two small bugs with lib-common.php and lib-topic.php (both undefined array index) so far.  However, I haven't come across serious errors except installer (which I haven't tested fully).

**Comment by mystralkk** [comment] 2019-10-01 11:27
I fixed some errors with Autotags, and it seems to work fine with PHP 7.3.

**Comment by eSilverStrike** [comment] 2019-10-01 14:20
How about Media Gallery? I forget where we left this plugin.

I will make sure to release these updated plugins when Geeklog 2.2.1 is released.

**Comment by mystralkk** [comment] 2019-10-01 21:26
Original - https://github.com/dengenxp/MediaGallery - last updated Jun 2015
Forked   - https://github.com/ivywe/MediaGallery        - last updated Feb 2016
              - https://github.com/mystralkk/MediaGallery  - last updated Oct 2017

**Comment by mystralkk** [comment] 2019-10-06 06:00
I updated MediaGallery ( https://github.com/mystralkk/MediaGallery ) and it seems to work fine.

**Comment by mystralkk** [comment] 2019-10-18 13:16
I updated the messenger plugin and it seems to work with PHP 7.3.  Is anyone still using the plugin?

**Comment by eSilverStrike** [comment] 2019-10-18 13:37
Not with a resent version of Geeklog at least since it still used COM_Siteheader, etc... 
What version number did you bump it to? I will add it to the list for release in #825

**Comment by mystralkk** [comment] 2019-10-18 13:43
I haven't bumped it up since I haven't fully confirmed if it works fine.  Currently, it seems to work well.  As soon as I have made sure it works properly, I will bump the version number up.

**Comment by mystralkk** [comment] 2019-10-19 08:05
I updated the version number of the messenger plugin to v1.9.0.

**Comment by mystralkk** [comment] 2022-01-17 05:28
Created a new repository for plugin information: https://github.com/Geeklog-Core/Plugin-Compatibility-List .

**Comment by eSilverStrike** [comment] 2022-04-27 14:50
@mystralkk  For PHP 8 and 8.1, can we close this or are we missing anything major? 

I have done most of my testing on PHP 8 but have started recently on PHP 8.1. I haven't tested the installer yet but Plan on testing it soon.

**Comment by mystralkk** [comment] 2022-04-27 21:02
In my opinion, Geeklog works well on PHP 8.1 including the installer.  There might be some bugs hidden yet, but we can close this issue.

**Closed** 2022-06-26 19:07 UTC
Labels: Improvement
