### ISSUE TITLE
New Comment on Failed reCAPTCHA returns to home page

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#863] opened 2018-05-14 16:47 UTC
We should see if we can get this to redisplay the comment edit form with the recaptcha error message.

This will need to work with the setting if comment edit form is displayed on article page or on own page.

Should make sure it works with comments for other plugins.

**Comment by mystralkk** [comment] 2019-09-05 12:18
As for article, I fixed the bug with change set 6ed327f.

**Comment by mystralkk** [comment] 2019-09-13 22:04
As for the Polls plugin, the bug is fixed.

**Comment by mystralkk** [comment] 2019-11-17 11:23
As for the StaticPages plugin the bug is fixed with change set a86c5b6.

**Comment by mystralkk** [comment] 2019-11-17 22:49
As for the Forum plugin with reCAPTCHA V2(NOT Invisible), it works fine.  However, I cannot reproduce this bug with Invisible reCAPTCHA.  When Invisible reCAPTCHA detects a suspicious post to the forum, it shows a captcha consisting of image tiles with a question like "Choose all palm trees" and won't let the user post till he shows the right answer.

**Closed** 2019-11-28 21:55 UTC
Labels: Bug
