### ISSUE TITLE
W3C Markup validation for Geeklog.

### ISSUE THREAD

**Issue by darkshram** [Geeklog-Core/geeklog#839] opened 2018-03-27 13:08 UTC
Recently updated to 2.1.3 (I have been using Geeklog since version 1.3) and modified several files from my Geeklog installation tu make it comply with 100% of the W3C Markup validation. It just happens that Geeklog has a lot of `<script type=text/javascript">` that should be replaced by simply `<script>`. Plesase, just watch the following URL:

[https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.geeklog.net%2F](https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.geeklog.net%2F)

As you may see, Denim theme has too a lot of CSS and HTML obsolete code.

My website currently has no warnings or errors:

[https://validator.w3.org/nu/?doc=http%3A%2F%2Fwww.alcancelibre.org%2F](https://validator.w3.org/nu/?doc=http%3A%2F%2Fwww.alcancelibre.org%2F)

Each Geeklog release I have to modify lots of geeklog files. It would be nice to see that geeklog meets the standards without having to modify the code on every new installation.

**Comment by eSilverStrike** [comment] 2018-04-09 21:39
@dengenxp did you want me to take a look at this one for the denim and denim_three theme or did you want to do it? (it doesn't matter to me)

I'll check out the Modern Curve theme as well but I don't think it is worth the time to make it 100% validated.

**Comment by dengenxp** [comment] 2018-04-10 12:15
It's not a bug.
In HTML 5, the type attribute can be omitted.
However, it can not be omitted in HTML 4 or XHTML.

**Comment by eSilverStrike** [comment] 2018-04-10 13:16
The Geeklog.net url does validate according to the specified schema(s) but it does create warnings because of the script tag (along with the use of role some elements). 

I was wondering if we should check the doc types and then include the 'type=text/javascript"' part or not in the resource class. 

After looking into this a bit more maybe it's not worth worrying about (as they are only warnings). Should we close this issue then?

**Closed** 2019-09-21 12:06 UTC
Labels: Bug
